### ISSUE TITLE
Can someone explain this line? `{open && props.children}`

### ISSUE THREAD

**Issue by b96m** [fireship-io/229-multi-level-dropdown#14]
Can anyone explain the `{open && props.children}` here? I am having trouble understand its positioning and effect. It is on line 45 of the App.js file for reference

```javascript
function NavItem(props) {
  const [open, setOpen] = useState(false);

  return (
    <li className="nav-item">
      <a href="#" className="icon-button" onClick={() => setOpen(!open)}>
        {props.icon}
      </a>

      {open && props.children} // <- THIS CODE HERE
    </li>
  );
}
```

Thank you!

**Comment by kevin-guertin** [comment]
If open = true, then render the component's children here.

**Comment by b96m** [comment]
Any explanation on how that works? I would have expected an if statement for the open = true condition, then maybe {props.children} as the content. Thanks for answering by the way

**Comment by kevin-guertin** [comment]
It could have been written with a regular if statement, but it is using a short circuit conditional to make it just a one-liner. See here for an explanation: [https://codeburst.io/javascript-short-circuit-conditionals-bbc13ac3e9eb](https://codeburst.io/javascript-short-circuit-conditionals-bbc13ac3e9eb)

**Comment by b96m** [comment]
Awesome thanks for the help @kevin-guertin !
