### ISSUE TITLE
Enhancement: Close drop down when clicked outside of drop down menu.

### ISSUE THREAD

**Issue by aparnapatil01** [fireship-io/229-multi-level-dropdown#4]
Hi,

The drop down menu does not gets closed when clicked outside of menu. This could be taken as an enhancement.

--
Thanks

**Comment by gusflopes** [comment]
Tryied to do that by myself but couldn't make it work...  Couldn't find my way using "refs"

**Comment by drclohite** [comment]
I tried to see if 'react-onclickoutside' might work. I did succeed in making it work elsewhere but not in this application. By the way if anyone can solve this, let me know. I created a new issue that a resolution to this problem would help and that is about multiple dropdown menus - they overlap, so having a mechanism to close a dropdown would be very useful.

**Comment by aparnapatil01** [comment]
@drclohite  @gusflopes - Hey thanks for consideration and reply. I'll also give a try :)

**Comment by kr4chinin** [comment]
I have a bit raw but working solution. First of all, I found this custom hook for tracking clicks which where made outside a **reference element**, and changed it a little bit:

```
export function useClickOutside(
	elementRef: HTMLElement | null,
	buttonRef: HTMLElement | null,
	fn: () => void
) {
	useEffect(() => {
		function handleClickOutside(e: any) {
			if (e.target === buttonRef) {
				return
			}

			if (elementRef && !elementRef.contains(e.target)) {
				fn()
			}
		}
		document.addEventListener('mousedown', handleClickOutside)

		return () => {
			document.removeEventListener('mousedown', handleClickOutside)
		}
	}, [elementRef, fn])
}
```

Before we move on to the next step I shall say that I've changed project structure a little bit and I have two `NavrItem` components - **plain** and **with dropdown**:

_NavItem.tsx:_

```
interface NavItemProps {
	icon: React.ReactNode
}

const NavItem: FC<NavItemProps> = ({ icon }) => {
	return (
		<li className="nav-item">
			<a href="#" className="icon-button">
				{icon}
			</a>
		</li>
	)
}

export default NavItem
```

_NavItemWithDropdown.tsx:_

```
interface NavItemWithDropdownProps {
	icon: React.ReactNode
	children: React.ReactNode
	isOpen: boolean
	toggleDropdown: () => void
	setButtonRef: (ref: HTMLElement | null) => void
}

const NavItemWithDropdown: FC<NavItemWithDropdownProps> = ({
	icon,
	children,
	isOpen,
	toggleDropdown,
	setButtonRef
}) => {
	return (
		<li className="nav-item">
			<a
				href="#"
				className="icon-button"
				onClick={toggleDropdown}
				ref={setButtonRef} // <- Setting button ref, explanation down below
			>
				{icon}
			</a>

			{isOpen && children}
		</li>
	)
}

export default NavItemWithDropdown
```

`NavItemWithDropdown` getting as props state and some functions to handle dropdown behavior. Then, in the `NavbarComponent` I've created:
* State for opening/closing dropdown (`isOpen, setIsOpen`)
* State for dropdown elements's ref (`dropdownRef, setDropdownRef`)
* State for button element (`buttonRef, setButtonRef`) so `useClickOutside` won't track clicks on button which is capable for dropdown opening
* `toggle` and `close` functions

And I've passed `setDropdownRef` to `DropdownMenu` component. 

_Navbar.tsx:_

```
const Navbar = () => {
	const [isOpen, setIsOpen] = useState(false)

	function toggleDropdown() {
		setIsOpen(prev => !prev)
	}

	function handleCloseDropdown() {
		setIsOpen(false)
	}

	const [dropdownRef, setDropdownRef] = useState<HTMLElement | null>(null)
	const [buttonRef, setButtonRef] = useState<HTMLElement | null>(null)

	useClickOutside(dropdownRef, buttonRef, handleCloseDropdown)

	return (
		<nav className="navbar">
			<ul className="navbar-nav">
				<NavItem icon={<PlusIcon />} />
				<NavItem icon={<BellIcon />} />
				<NavItem icon={<MessengerIcon />} />

				<NavItemWithDropdown
					icon={<CaretIcon />}
					isOpen={isOpen}
					toggleDropdown={toggleDropdown}
					setButtonRef={setButtonRef}
				>
					<DropdownMenu setReferenceElement={setDropdownRef} />
				</NavItemWithDropdown>
			</ul>
		</nav>
	)
}

export default Navbar
```

_DropdownMenu.tsx:_

```
interface DropdownMenuProps {
	setReferenceElement: (ref: HTMLDivElement) => void
}

const DropdownMenu: FC<DropdownMenuProps> = ({ setReferenceElement }) => {
	const [menuHeight, setMenuHeight] = useState(0)
	const dropdownRef = useRef<any>(null)

	useEffect(() => {
		setReferenceElement(dropdownRef.current) // <- Setting ref
		setMenuHeight(dropdownRef.current?.firstChild.offsetHeight)
	}, [])

	function calcHeight(el: HTMLElement) {
		const height = el.offsetHeight
		setMenuHeight(height) 
	}

	return (
		<div className="dropdown" style={{ height: menuHeight }} ref={dropdownRef}> // <- Providing ref
			// CSSTransition and other logic...
		</div>
	)
}

export default DropdownMenu
```

That's it. Now everything is working and you can **close a dropdown by clicking outisde of it**. This method probably needs to have some improvements before being applied to production though. 
 
![Dropdown example](https://user-images.githubusercontent.com/103210607/186391043-912f958e-c26c-4296-8000-7e4b43fba9e4.gif)
